### ISSUE TITLE
Feature Request: API für dynamische Nachrichtenauslösung von externen Diensten

### ISSUE THREAD

**Issue by Oggy512** [sebiw/HermineBot#3]
Es wäre schön, wenn HermineBot eine API bieten würde, an welche man von einem externen Dienst Daten übergeben kann um so eine Nachricht an einen Channel schreiben zu können.
Somit wäre die Möglichkeit gegeben, z.B. über NodeRed oder per einfachem Webrequest automatisiert Informationen verteilen zu können.
Anwendungsfällt sind z.B. Übergabe von Alarmierungsinformationen in einen Channel, automatische (System)überwachungsmeldung an die IT Gruppe etc pp

**Comment by sebiw** [comment]
Dein Feature-Wunsch wurde mit dem letzten Commit https://github.com/sebiw/HermineBot/commit/f7e8996e07a28df98ef365d6dfbcbb93097f2748 umgesetzt.

Dabei sind nun folgende Änderungen zu beachten:
- in der Datenbank muss dein aktueller Nutzer die Rolle `["ROLE_ADMIN"]` besitzen
- Du kannst nun einen neuen API-User anlegen der die Rolle `["ROLE_API"]` haben muss, das Passwort kannst du mittels `php bin/console security:hash-password` für diesen Nutzer erstellen

Mittels diesem Nutzer solltest du nun mittel POST folgendes durchführen können, also User/Password sowie Channel/Message mittels JSON-Content via HTTP-POST übermitteln. Die Nachricht sollte dann übermittelt werden.

> POST http://hermine-bot.localhost/api/send-message
> Accept: application/json
> Content-Type: application/json
> 
> {
> "user" : "api",
> "key" : "password",
> "channel" : "DEIN_CHANNEL_NAME",
> "message" : "ICH BIN DER NACHRICHTENTEXT"
> }
