### ISSUE TITLE
Feature Request: Message an User 

### ISSUE THREAD

**Issue by Oggy512** [sebiw/HermineBot#4]
Es wäre schön, wenn HermineBot die Möglichkeit hätte, Nachrichten auch an (einzelne) User zu schicken.

**Comment by sebiw** [comment]
Hey!
Ich habe soeben den Commit https://github.com/sebiw/HermineBot/commit/ccc38a1f9960a722edcdb4e0d7667d088121f953 im master bereitgestellt. Dieses bietet nun die Möglichkeit entweder via Konsolen-Befehl  `php bin/console hermine:send-message --conversationId=1234567890 --message="Nachrichtentext"` oder via zuletzt bereitgestellter REST-Api via:

> POST http://hermine-bot.localhost/api/send-message
> Accept: application/json
> Content-Type: application/json
> 
> {
> "user" : "api",
> "key" : "password",
> "conversationId" : "1234567890",
> "message" : "ICH BIN DER NACHRICHTENTEXT"
> }

Eine Nachricht in eine zuvor erstellte Konversation zu schicken. Dabei muss jedoch vorerst die Konversation initial erstellt worden sein in Hermine. Die ID findet man unter anderem im Web-Client innerhalb der URL: 
https://app.thw-messenger.de/thw/app#/chats/messages/conversation/__HIER_STEHT_DIE_ID__

Reicht dir das? Denke aus Sicherheits-Sicht ist das vertretbar - da du für die Einrichtung immerhin vorher eine manuelle Erstellung durchführen musstest.
